management/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('present.urls')),
]

present/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home-page'),
    path('tablepage/', views.tablepage, name='tablepage'),
    
    path('delete_view/<id>/', views.delete_view, name='delete_view'),
    path('update_view/<id>', views.update_view, name='update_view'),
    path('evaluation_list', views.evaluation_list, name='evaluation_list'),
    path('edit/<int:pk>/', views.evaluation_edit, name='evaluation_edit'),
    path('new/', views.evaluation_edit, name='evaluation_new'),
    path('rate/', views.rating_view, name='rating_view'),
    path('filter/', views.filter_evaluations, name='filter_evaluations'),


    path('add_name_roll/', views.add_name_roll, name='add_name_roll'),
    path('add_idea_no_listz', views.add_idea_no_listz, name='add_idea_no_listz'),
   
    path('add_idea_no/', views.add_idea_no, name='add_idea_no'), #grpup,idea 1 idea 2 idea 3
    path('update_idea_no/<int:pk>/', views.update_idea_no, name='update_idea_no'),
    path('delete_idea_no/<int:pk>/', views.delete_idea_no, name='delete_idea_no'),
    path('send_test_smtp_email/', views.send_test_smtp_email, name='send_test_smtp_email'),
    
    
    #  path('delete/<int:group_id>/', views.delete_idea_student, name='delete_idea_student'),
    path('check_plagiarism/<int:group_id>/', views.check_plagiarism, name='check_plagiarism'),
    path('finalize_idea_page/<int:group_id>/', views.finalize_idea_page, name='finalize_idea_page'),
    path('evaluation_list_form/', views.evaluation_list_form, name='evaluation_list_form'),


    # ty
    path('ty_list/', views.ty_evaluation_list, name='ty_evaluation_list'),
    path('ty_new/', views.ty_evaluation_edit, name='ty_evaluation_new'),
    path('ty_delete_view/<id>/', views.ty_delete_view, name='ty_delete_view'),
    path('ty_update_view/<id>', views.ty_update_view, name='ty_update_view'),
    path('ty_filter_by_branch_and_year/', views.ty_filter_evaluations, name='ty_filter_evaluations'),
    path('ty_add_grp_no_grp_idea/', views.ty_add_grp_no_grp_idea, name='ty_add_grp_no_grp_idea'),

    # ty
    path('ly_list/', views.ly_evaluation_list, name='ly_evaluation_list'),
    path('ly_new/', views.ly_evaluation_edit, name='ly_evaluation_new'),
    path('ly_delete_view/<id>/', views.ly_delete_view, name='ly_delete_view'),
    path('ly_update_view/<id>', views.ly_update_view, name='ly_update_view'),
    path('ly_filter_by_branch_and_year/', views.ly_filter_by_branch_and_year, name='ly_filter_by_branch_and_year'),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

present/models.py
from django.db import models


class Sy_add_idea_no(models.Model):
    Add_sy_group_no = models.IntegerField()
    
    CHOICES_GUIDE = [
        ('0', 'None'),
        ('1', 'A'),
        ('2', 'B'),
        ('3', 'C'),
        ('4', 'D'),
        ('5', 'E'),
    ]
    CHOICES_BRANCH = [
        ('0', 'NONE'),
        ('1', 'IT'),
        ('2', 'COMPS'),
        ('3', 'AIDS'),
        ('4', 'EXTC'),
    ]
    CHOICES_YEAR = [
        ('0', 'None'),
        ('1', '2023'),
        ('2', '2024'),
        ('3', '2025'),
        ('4', '2026'),
        ('5', '2027'),
        ('6', '2028'),
        ('7', '2029'),
        ('8', '2030'),
        ('9', '2031'),
        ('10', '2032'),
    ]

    sy_idea_1 = models.CharField(max_length=60)
    sy_idea_1_des = models.TextField(max_length=300)

    sy_idea_2 = models.CharField(max_length=60)
    sy_idea_2_des = models.TextField(max_length=300)
    
    sy_idea_3 = models.CharField(max_length=60)
    sy_idea_3_des = models.TextField(max_length=300)
    
    choices_guide = models.CharField(
        max_length=20,
        choices=CHOICES_GUIDE,
        default='0'
    )
    choices_branch = models.CharField(
        max_length=20,
        choices=CHOICES_BRANCH,
        default='0'
    )
    choices_year = models.CharField(
        max_length=20,
        choices=CHOICES_YEAR,
        default='0'
    )

    def get_grp_no(self):
        return self.Add_sy_group_no
    
    def get_sy_idea_1(self):
        return self.sy_idea_1
    
    def get_sy_idea_1_description(self):
        return self.sy_idea_1_des
    
    def get_sy_idea_2(self):
        return self.sy_idea_2
    
    def get_sy_idea_2_description(self):
        return self.sy_idea_2_des
    
    def get_sy_idea_3(self):
        return self.sy_idea_3
    
    def get_sy_idea_3_description(self):
        return self.sy_idea_3_des
    
    def get_choices_guide(self):
        return dict(self.CHOICES_GUIDE).get(self.choices_guide, 'Unknown')
    
    def get_choices_branch(self):
        return dict(self.CHOICES_BRANCH).get(self.choices_branch, 'Unknown')
    
    def get_choices_year(self):
        return dict(self.CHOICES_YEAR).get(self.choices_year, 'Unknown')

    def __str__(self):
        return (f'Group No: {self.Add_sy_group_no}, '
                f'Guide: {self.get_choices_guide()}, '
                f'Branch: {self.get_choices_branch()}, '
                f'Year: {self.get_choices_year()}')
    



class Sy_idea_no(models.Model):
    sy_name = models.CharField(max_length=100)
    sy_roll_no = models.IntegerField()
    sy_email = models.CharField(max_length=100,default='@somaiya.edu')
    sy_group_no = models.ForeignKey(Sy_add_idea_no, on_delete=models.CASCADE)
    def __str__(self):
        return f'Name : {self.sy_name}, Group No: {self.sy_group_no.Add_sy_group_no}, Branch: {self.sy_group_no.get_choices_branch()}, Guide: {self.sy_group_no.get_choices_guide()},Year: {self.sy_group_no.get_choices_year()}'


class final_idea(models.Model):
    final_title = models.ForeignKey(Sy_add_idea_no, on_delete=models.CASCADE)
    selected_idea = models.CharField(max_length=60)

    def __str__(self):
        return f' Selected Idea: {self.selected_idea} ,Group: {self.final_title.Add_sy_group_no}, Branch: {self.final_title.get_choices_branch()}'



CHOICES01 = [
    ('1', 'Student is Present'),
    ('0', 'Student is Absent'),
    ('2', 'The presentation has not been conducted yet')

]


CHOICES1 = [
   
    ('5', 'Cites substantial current quality literature(5)'),
    ('4', 'Cites reasonable quantity of current quality literature(4)'),
    ('3', 'Cites current literature(3)'),
    ('2', 'Does not cite any current quality literature(2)'),
    ('0', 'Assign zero marks.'),
]

CHOICES2 = [
       
    ('5', 'Provides good understanding of literature cited(5)'),
    ('4', 'Provides understanding of literature cited(4)'),
    ('3', 'Exhibits poor understanding of literature cited(3)'),
    ('2', 'Very poor in understanding literature cited(2)'),
        ('0', 'Assign zero marks.'),
]

CHOICES3 = [
       
    ('10', 'Very good clarity about the subject matter'),
    ('8', 'Somewhat good clarity'),
    ('6', 'Not so good clarity'),
    ('4', 'Very poor'),
        ('0', 'Assign zero marks.'),
]

CHOICES4 = [
       
    ('3', 'Written in own, grammatically correct language'),
    ('2.4', 'Written in own language, has many grammatical errors'),
    ('1.8', 'Language not good'),
    ('1.2', 'Mostly copied'),
    ('0', 'Assign zero marks.'),
]

CHOICES5 = [
       
    ('2', 'Recommended format used'),
    ('1.4', 'Mostly in recommended format'),
    ('1.2', 'Many deviations from format'),
    ('0.8', 'No format'),
        ('0', 'Assign zero marks.'),
]

CHOICES6 = [
       
    ('3', 'Very good presentation'),
    ('2.4', 'Somewhat good presentation'),
    ('1.8', 'Messy presentation'),
    ('1.2', 'Very poor presentation'),
        ('0', 'Assign zero marks.'),
]

CHOICES7 = [
       
    ('2', 'Very good Communication Skill'),
    ('1.4', 'Good Communication Skill'),
    ('1.2', 'Poor Communication Skill'),
    ('0.8', 'Very poor Communication Skill'),
        ('0', 'Assign zero marks.'),
]

CHOICES8 = [
       
    ('10', 'International (Refereed) print Journal'),
    ('8', 'National (Refereed) print Journal'),
    ('6', 'International (Refereed) Conference'),
    ('4', 'National (Refereed) Conference and Online Journal'),
        ('0', 'Assign zero marks.'),
]

CHOICES9 = [
       
    ('2.5', 'Highly effective communication'),
    ('2.0', 'Good communication'),
    ('1.5', 'Adequate communication'),
    ('1.0', 'Ineffective communication'),
        ('0', 'Assign zero marks.'),
]

CHOICES10 = [
       
    ('2.5', 'Equal contribution from all members'),
    ('2.0', 'Good contribution from most members'),
    ('1.5', 'Uneven contribution'),
    ('1.0', 'Poor contribution from members'),
        ('0', 'Assign zero marks.'),
]

CHOICES11 = [
       
    ('2.5', 'Excellent coordination'),
    ('2.0', 'Good coordination'),
    ('1.5', 'Adequate coordination'),
    ('1.0', 'Poor coordination'),
        ('0', 'Assign zero marks.'),
]

CHOICES12 = [
    
    ('2.5', 'Excellent coordination'),
    ('2.0', 'Good coordination'),
    ('1.5', 'Adequate coordination'),
    ('1.0', 'Poor coordination'),
        ('0', 'Assign zero marks.'),
]




 

class FinalMarksEvaluation(models.Model):
    final_marks_evaluation = models.ForeignKey(final_idea, on_delete=models.CASCADE)
    final_marks_student = models.ForeignKey(Sy_idea_no, on_delete=models.CASCADE)

    # Fields for P1 Marks Evaluation
    num01 = models.CharField(max_length=60, choices=CHOICES01, default='2')
    num1 = models.CharField(max_length=60, choices=CHOICES1, default='0')
    num2 = models.CharField(max_length=60, choices=CHOICES2, default='0')
    num21 = models.CharField(max_length=60, choices=CHOICES3, default='0')
    num31 = models.CharField(max_length=60, choices=CHOICES4, default='0')
    num32 = models.CharField(max_length=60, choices=CHOICES5, default='0')
    num33 = models.CharField(max_length=60, choices=CHOICES6, default='0')
    num34 = models.CharField(max_length=60, choices=CHOICES7, default='0')
    num41 = models.CharField(max_length=60, choices=CHOICES8, default='0')
    num51 = models.CharField(max_length=60, choices=CHOICES9, default='0')
    num52 = models.CharField(max_length=60, choices=CHOICES10, default='0')
    num53 = models.CharField(max_length=60, choices=CHOICES11, default='0')
    num54 = models.CharField(max_length=60, choices=CHOICES12, default='0')


    # Fields for P2 Marks Evaluation
    p2_num01 = models.CharField(max_length=60, choices=CHOICES01, default='2')
    p2_num1 = models.CharField(max_length=60, choices=CHOICES1, default='0')
    p2_num2 = models.CharField(max_length=60, choices=CHOICES2, default='0')
    p2_num21 = models.CharField(max_length=60, choices=CHOICES3, default='0')
    p2_num31 = models.CharField(max_length=60, choices=CHOICES4, default='0')
    p2_num32 = models.CharField(max_length=60, choices=CHOICES5, default='0')
    p2_num33 = models.CharField(max_length=60, choices=CHOICES6, default='0')
    p2_num34 = models.CharField(max_length=60, choices=CHOICES7, default='0')
    p2_num41 = models.CharField(max_length=60, choices=CHOICES8, default='0')
    p2_num51 = models.CharField(max_length=60, choices=CHOICES9, default='0')
    p2_num52 = models.CharField(max_length=60, choices=CHOICES10, default='0')
    p2_num53 = models.CharField(max_length=60, choices=CHOICES11, default='0')
    p2_num54 = models.CharField(max_length=60, choices=CHOICES12, default='0')


    # Fields for P3 Marks Evaluation
    p3_num01 = models.CharField(max_length=60, choices=CHOICES01, default='2')
    p3_num1 = models.CharField(max_length=60, choices=CHOICES1, default='0')
    p3_num2 = models.CharField(max_length=60, choices=CHOICES2, default='0')
    p3_num21 = models.CharField(max_length=60, choices=CHOICES3, default='0')
    p3_num31 = models.CharField(max_length=60, choices=CHOICES4, default='0')
    p3_num32 = models.CharField(max_length=60, choices=CHOICES5, default='0')
    p3_num33 = models.CharField(max_length=60, choices=CHOICES6, default='0')
    p3_num34 = models.CharField(max_length=60, choices=CHOICES7, default='0')
    p3_num41 = models.CharField(max_length=60, choices=CHOICES8, default='0')
    p3_num51 = models.CharField(max_length=60, choices=CHOICES9, default='0')
    p3_num52 = models.CharField(max_length=60, choices=CHOICES10, default='0')
    p3_num53 = models.CharField(max_length=60, choices=CHOICES11, default='0')
    p3_num54 = models.CharField(max_length=60, choices=CHOICES12, default='0')


    # Fields for P4 Marks Evaluation
    p4_num01 = models.CharField(max_length=60, choices=CHOICES01, default='2')
    p4_num1 = models.CharField(max_length=60, choices=CHOICES1, default='0')
    p4_num2 = models.CharField(max_length=60, choices=CHOICES2, default='0')

present/myapp/templates/myapp_ly/ly_delete_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>Delete</title>
    <link rel="stylesheet" href="{% static 'css/deletepage.css' %}">
</head>
<body>
    <div class="main">
        <!-- Create a Form -->
        <form method="POST">
            <!-- Security token by Django -->
            {% csrf_token %}
            <p>Are you sure you want to delete this item?</p>
            <div class="buttons">
                <input type="submit" value="Yes" class="submit-btn" />
                <a href="/" class="cancel-btn">Cancel</a>
            </div>
        </form>
    </div>
</body>
</html>

present/myapp/templates/myapp_ly/ly_evaluation_edit.html
<!DOCTYPE html>
<html>

<head>
    <title>Edit Group Evaluation</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/add.css' %}">

</head>

<body>
    <div class="container">
        <h1>Add Group Marks Evaluation</h1>
        <form method="POST">
            {% csrf_token %}
            

            <p>
                <label for="id_group_no">Group no:</label>
                {{ form.group_no }}
                <!-- <input type="number" name="group_no" required aria-invalid="true" id="id_group_no"> -->
            </p>

            <p>
                <label for="id_group_name">Group name:</label>
                {{ form.group_name }}
                <!-- <input type="text" name="group_name" maxlength="255" required id="id_group_name"> -->
            </p>

            <p>
                <label for="id_group_idea">Group idea:</label>
                {{ form.group_idea }}
                <!-- <input type="text" name="group_idea" maxlength="255" required id="id_group_idea"> -->
            </p>

            <p>
                <label for="id_group_year">Group year:</label>
                {{ form.group_year }}
                <!-- <input type="text" name="group_year" maxlength="4" required id="id_group_year"> -->
            </p>

            <p>
                <label for="id_num01">Select Branch:</label>
                {{ form.num01 }}
                <select name="num01" id="id_num01" required>
                    <option value="None" {% if form.num01.value == 'None' %}selected{% endif %}>None</option>
                    <option value="IT" {% if form.num01.value == 'IT' %}selected{% endif %}>IT</option>
                    <option value="COMPS" {% if form.num01.value == 'COMPS' %}selected{% endif %}>COMPS</option>
                    <option value="AIDS" {% if form.num01.value == 'AIDS' %}selected{% endif %}>AIDS</option>
                    <option value="EXTC" {% if form.num01.value == 'EXTC' %}selected{% endif %}>EXTC</option>
                </select>
            </p>
            

           
            <p>
                <label>
                    <h3>Substantial current and good quality literature (10) :</h3>
                </label>
                
                <div class="radio-group">
                    <label><input type="radio" name="num1" value="5"> Cites substantial current quality literature (5)</label>
                    <label><input type="radio" name="num1" value="4"> Cites reasonable quantity of current quality literature (4)</label>
                    <label><input type="radio" name="num1" value="3"> Cites current literature (3)</label>
                    <label><input type="radio" name="num1" value="2" checked> Does not cite any current quality literature (2)</label>
                </div>
            </p>

            <p>
                
                <div class="radio-group">
                    <label><input type="radio" name="num2" value="5"> Provides good understanding of literature cited (5)</label>
                    <label><input type="radio" name="num2" value="4"> Provides understanding of literature cited (4)</label>
                    <label><input type="radio" name="num2" value="3"> Exhibits poor understanding of literature cited (3)</label>
                    <label><input type="radio" name="num2" value="2" checked> Very poor in understanding literature cited (2)</label>
                </div>
            </p>

            <p>
                <label>
                    <h3>Answering Questions Posed by Examiner (10) :</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num21" value="10"> Very good clarity about the subject matter</label>
                    <label><input type="radio" name="num21" value="8"> Somewhat good clarity</label>
                    <label><input type="radio" name="num21" value="6"> Not so good clarity</label>
                    <label><input type="radio" name="num21" value="4" checked> Very poor</label>
                </div>
            </p>

            <p>
                <label>
                    <h3>Presentation skills (10):</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num31" value="4"> Written in own, grammatically correct language</label>
                    <label><input type="radio" name="num31" value="3.2" checked> Written in own language, has many grammatical errors</label>
                    <label><input type="radio" name="num31" value="2.4"> Language not good</label>
                    <label><input type="radio" name="num31" value="1.6"> Mostly copied</label>
                </div>
            </p>

            <p>
            
                <div class="radio-group">
                    <label><input type="radio" name="num32" value="4"> Very good presentation</label>
                    <label><input type="radio" name="num32" value="3.2" checked> Somewhat good presentation</label>
                    <label><input type="radio" name="num32" value="2.4"> Messy presentation </label>
                    <label><input type="radio" name="num32" value="1.6"> Very poor presentation </label>
                </div>
            </p>

            <p>
               
                <div class="radio-group">
                    <label><input type="radio" name="num33" value="2"> Recommended format used</label>
                    <label><input type="radio" name="num33" value="1.6" checked> Mostly in recommended format </label>
                    <label><input type="radio" name="num33" value="1.2"> Many deviations from format</label>
                    <label><input type="radio" name="num33" value="0.8"> No format </label>
                </div>
            </p>
            <p>
                <label>
                    <h3>Communication skills (10):</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num41" value="10">Very good Communication Skill</label>
                    <label><input type="radio" name="num41" value="8"> Good Communication Skill</label>
                    <label><input type="radio" name="num41" value="6"> Poor Communication Skill</label>
                    <label><input type="radio" name="num41" value="4" checked> Very poor Communication Skill</label>
                </div>
            </p>
           
            <p>
                <label>
                    <h3>Quality of Research Paper (10):</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num51" value="10"> International (Refereed) print Journal</label>
                    <label><input type="radio" name="num51" value="8"> National (Refereed) print Journal</label>
                    <label><input type="radio" name="num51" value="6"> International (Refereed) Conference</label>
                    <label><input type="radio" name="num51" value="4" checked> National (Refereed) Conference and Online Journal</label>
                </div>
            </p>
            <p>
                <label>
                    <h3>Teamwork and Collaboration (10):</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num61" value="10"> Highly effective communication and Equal contribution from all members </label>
                    <label><input type="radio" name="num61" value="8"> Good communication and good contribution from most members </label>
                    <label><input type="radio" name="num61" value="6"> Adequate communication and uneven contribution</label>
                    <label><input type="radio" name="num61" value="4" checked> Ineffective communication and poor contribution from members</label>
                </div>
            </p>
            <p>
                <label>
                    <h3>Documentation and Reporting (10):</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num71" value="10"> Very clear, concise, well organized and logical </label>
                    <label><input type="radio" name="num71" value="8"> Mostly clear, concise and organized</label>
                    <label><input type="radio" name="num71" value="6"> Somewhat clear, concise and organized</label>
                    <label><input type="radio" name="num71" value="4" checked> Lacks clarity and conciseness and Poorly organized</label>
                </div>
            </p>

       
            <p>
                <label>
                    <h3>Originality (10):</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num81" value="10"> Highly innovative and original </label>
                    <label><input type="radio" name="num81" value="8"> Some innovation and originality</label>
                    <label><input type="radio" name="num81" value="6"> Minimal innovation and originality</label>
                    <label><input type="radio" name="num81" value="4" checked> Lacks innovation and originality</label>
                </div>
            </p>

       
            <p>
                <label>
                    <h3>Creativity (10):</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num91" value="10">Demonstrates exceptional creativity</label>
                    <label><input type="radio" name="num91" value="8">Shows good creativity</label>
                    <label><input type="radio" name="num91" value="6"> Demonstrates average creativity</label>
                    <label><input type="radio" name="num91" value="4" checked> Lacks creativity</label>
                </div>
            </p>
       
            <p>
                <label>
                    <h3>Design and Technical Feasibility (10):</h3>
                </label>
                <div class="radio-group">
                    <label><input type="radio" name="num101" value="10"> Design is highly effective and it is highly feasible and practical </label>
                    <label><input type="radio" name="num101" value="8"> Design is mostly effective and technically feasible and practical</label>
                    <label><input type="radio" name="num101" value="6"> Design is somewhat effective and feasibility is questionable</label>
                    <label><input type="radio" name="num101" value="4" checked> Design is ineffective and neither feasible nor practical</label>
                </div>
            </p>

       
        
            <p>
                <label for="id_oral_practical">Oral practical:</label>
             
                <input type="number" name="oral_practical"  required id="id_oral_practical">
            </p>
          
            <button type="submit">Save</button>
        </form>

        <a href="{% url 'ly_evaluation_list' %}">Back to List</a>
    </div>
</body>
</html>

present/myapp/templates/myapp_ly/ly_evaluation_list.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>Group Evaluation List</title>
    <link rel="stylesheet" href="{% static 'css/tablepage.css' %}">
 
</head>
<body>
    <h1>Group Evaluation List</h1>
    
    <div class="table-container">
        <div class="header">
        <button class="button-62" role="button">
            <a href="{% url 'ly_evaluation_new' %}">Add New Evaluation</a>
        </button>

        <!-- Combined Filter Form -->
        <div class="form-container">
            <form method="GET" action="{% url 'ly_filter_by_branch_and_year' %}">
                <div class="branch">
                <label class="branch_label"  for="branch">Select Branch:</label>
                <select name="branch" id="branch">
                    <option value="">--Select Branch--</option>
                    <option value="IT">IT</option>
                    <option value="COMPS">COMPS</option>
                    <option value="AIDS">AIDS</option>
                    <option value="EXTC">EXTC</option>
                </select>
            </div>
            <div class="year">
                <label for="year">Select Year:</label>
                <select name="year" id="year">
                    <option value="">--Select Year--</option>
                    <option value="2023">2023</option>
                    <option value="2024">2024</option>
                    <option value="2025">2025</option>
                    <option value="2026">2026</option>
                    <option value="2027">2027</option>
                    <option value="2028">2028</option>
                    <option value="2029">2029</option>
                    <option value="2030">2030</option>
                    <option value="2031">2031</option>
                    <option value="2032">2032</option>
                    <option value="2034">2034</option>
                    <option value="2035">2035</option>
                    <option value="2036">2036</option>
                    <option value="2037">2037</option>
                    <option value="2038">2038</option>
                    <option value="2039">2039</option>
                </select>
            </div>
                

        

                <button class="filter_btn" type="submit">Filter</button>
            </form>
        </div>
        
    </div>
        <br>

        <table>
            <thead>
                <tr>
                    <th>Group No.</th>
                    <th>Group Name</th>
                    <th>Group Idea</th>
                    <th>Branch</th>
                    <th>Year</th>
                    <th>Substantial current and good quality literature (10)</th>
                    <th>Answering Questions Posed by Examiner (10)</th>
                    <th>Presentation skills(10)</th>
                    <th>Communication skills(10)</th>
                    <th>Quality of Research Paper (10)</th>
                    <th>Teamwork and Collaboration</th>
                    <th>Documentation and Reporting (10)</th>
                    <th>Originality (10)</th>
                    <th>Creativity (10)</th>
                    <th>Design and Technical Feasibility  (10)</th>
                    <th>Avg Teamwork</th>
                    <th>Oral/Practical</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for evaluation in evaluations %}
                <tr>
                    <td>{{ evaluation.group_no }}</td>
                    <td>{{ evaluation.group_name }}</td>
                    <td>{{ evaluation.group_idea }}</td>
                    <td>{{ evaluation.num01 }}</td>
                    <td>{{ evaluation.group_year }}</td>
                    <td>{{ evaluation.eval1_total }}</td>
                    <td>{{ evaluation.eval2_total }}</td>
                    <td>{{ evaluation.eval3_total }}</td>
                    <td>{{ evaluation.eval4_total }}</td>
                    <td>{{ evaluation.eval5_total }}</td>
                    <td>{{ evaluation.eval6_total }}</td>
                    <td>{{ evaluation.eval7_total }}</td>
                    <td>{{ evaluation.eval8_total }}</td>
                    <td>{{ evaluation.eval9_total }}</td>
                    <td>{{ evaluation.eval10_total }}</td>
                    <td>{{ evaluation.calculate_teamwork }}</td>
                    <td>{{ evaluation.oral_practical }}</td>
                    <td class="actions">
                        <div class="button_up">     
                            <a href="{% url 'ly_update_view' evaluation.id %}">Update</a> 
                        </div>
                        |
                        <div class="button_del">     
                            <a href="{% url 'ly_delete_view' evaluation.id %}">Delete</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr>
   
    </div>
</body>
</html>

present/myapp/templates/myapp_ly/ly_update_view.html
<!-- evaluation_edit.html -->
<!DOCTYPE html>
<html>

<head>
    <title>Update Evaluation</title>
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
</head>

<body>
    <div class="container">
        <h1>Update Group Evaluation</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Save</button>
        </form>

        <a href="{% url 'ly_evaluation_list' %}">Back to List</a>
    </div>
</body>

</html>